INSERT INTO local (name, address, description, "pricePerDay", lat, lng, "isReserved") VALUES
('Studio Ghibli v2', '5544 Rue Saint-Michel, Montreal', 'Beautiful house in downtown Montreal', 125.89, 46.6, -76.7, false),
('L''Atelier Cathcart', '802 Rue Cathcart, Montréal, QC', 'Espace de travail lumineux au cœur du centre-ville, idéal pour bureaux créatifs ou showrooms. Grandes fenêtres, plafonds hauts et finitions industrielles modernes.', 120, 45.501, -73.570, false),
('Studio Cathcart', '741 Rue Cathcart, Montréal, QC', 'Local polyvalent en plein centre-ville, parfait pour ateliers, pop-ups ou espaces de coworking. Accès facile en transport en commun, stationnement à proximité.', 95, 45.501, -73.569, false),
('Espace Centrale', '638 Rue Cathcart, Montréal, QC', 'Bureau moderne et épuré, situé à deux pas de la Place du Canada. Convient parfaitement aux réunions d''affaires, formations ou événements corporatifs intimistes.', 85, 45.503, -73.568, false),
('Le Loft Sherbrooke', '626 Rue Sherbrooke O, Montréal, QC', 'Magnifique loft avec vue sur la rue Sherbrooke, dans un bâtiment patrimonial rénové. Ambiance chaleureuse, brique apparente et poutres en bois. Idéal pour galeries ou bureaux de prestige.', 150, 45.505, -73.573, false),
('Bureau Neiges I', '5845 Chem. de la Côte-des-Neiges, Montréal, QC', 'Local commercial bien situé sur la Côte-des-Neiges, à proximité de l''Université de Montréal. Espace ouvert et modulable, adapté aux cliniques, cabinets ou commerces de détail.', 75, 45.500, -73.630, false),
('Bureau Neiges II', '5920 Chem. de la Côte-des-Neiges, Montréal, QC', 'Espace lumineux au deuxième étage avec vue dégagée sur le quartier. Idéal pour professionnels de la santé, conseillers ou tuteurs. Accès PMR disponible.', 70, 45.500, -73.630, false),
('La Salle Blanche', '5858 Chem. de la Côte-des-Neiges, Montréal, QC', 'Local immaculé aux murs blancs, parfait pour photographes, artistes ou espaces de bien-être. Lumière naturelle abondante et atmosphère zen dans un quartier dynamique.', 90, 45.499, -73.629, false),
('L''Annexe CDN', '5779 Chem. de la Côte-des-Neiges, Montréal, QC', 'Petit local discret et fonctionnel, idéal pour une activité indépendante ou un bureau satellite. Loyer compétitif dans l''un des quartiers les plus vivants de Montréal.', 60, 45.499, -73.628, false),
('L''Entrepôt Louvain', '1030 Rue Louvain, Montréal, QC', 'Vaste entrepôt reconverti dans le quartier Ahuntsic, offrant un espace brut et généreux. Plafonds de 5 mètres, quai de chargement et accès camion. Parfait pour stockage, production ou événements alternatifs.', 110, 45.557, -73.647, false)
ON CONFLICT DO NOTHING;