### Register user test
POST http://localhost:3000/v1/auth/register
Content-Type: application/json 

{
    "email":"ohHiSS@gmail.com",
    "password":"WelcomeToRentALFE5553543////ocal",
    "firstName":"HowCanI",
    "lastName":"HelpYou"
}

### Login user test
POST http://localhost:3000/v1/auth/login
Content-Type: application/json 

{
    "email":"sasa@yolo.com",
    "password":"123SASAsasa$$$#$##$#$#$#@@"
}

### Get user profile test
GET http://localhost:3000/v1/auth/profile
Cookie: session=eyJ0b2tlbiI6eyJhY2Nlc3NfdG9rZW4iOiJleUpoYkdjaU9pSklVekkxTmlJc0luUjVjQ0k2SWtwWFZDSjkuZXlKemRXSWlPakVzSW1WdFlXbHNJam9pYzJGellVQjViMnh2TG1OdmJTSXNJbkp2YkdVaU9pSjFjMlZ5SWl3aWFXRjBJam94TnpjME5EVXdORGcxTENKbGVIQWlPakUzTnpRME5UUXdPRFY5LjdwbnY5WDd6cUpnRWNSb29WNmFOckxhYURNaVZmVGdab2tqLUJHdy1DS1UifX0=; path=/; expires=Wed, 25 Mar 2026 15:54:45 GMT; httponly

### List all users
GET http://localhost:3000/v1/users

### Find 1 user
GET http://localhost:3000/v1/users/1

### Update user
PATCH http://localhost:3000/v1/users/2

### Delete a user
DELETE http://localhost:3000/v1/users/2

#### RESERVATIONS

### List all reservations
GET http://localhost:3000/v1/reservations

### Find 1 reservation
GET http://localhost:3000/v1/reservations/3

### Create a new reservation
POST http://localhost:3000/v1/reservations
Content-Type: application/json

{
    "startDate": "2026-06-11",
    "endDate": "2026-07-17",
    "userId": 1
}

### Update a reservation
PATCH http://localhost:3000/v1/reservations/3
Content-Type: application/json

{
    "endDate": "2026-03-31"
}

### Delete a reservation
DELETE http://localhost:3000/v1/reservations/2

### Create a new local
POST http://localhost:3000/v1/locals
Content-Type: application/json

{
    "name": "Studio downtown",
    "address": "123 Rue Sainte-Catherine, Montreal",
    "description": "Beautiful studio in the heart of downtown",
    "pricePerDay": 89.99
}

### List all locals
GET http://localhost:3000/v1/locals

### Find a local by ID
GET http://localhost:3000/v1/locals/1

### Update a local
PATCH http://localhost:3000/v1/locals/1
Content-Type: application/json

{
    "pricePerDay": 99.99,
    "description": "Beautiful studio with wifi and AC"
}

### Delete a local
DELETE http://localhost:3000/v1/locals/1