### create user test
POST http://localhost:3000/auth/signup/
Content-Type: application/json

{
    "email" : "abc@def.ghi",
    "password": "jklmnop"
}

### signin user
POST http://localhost:3000/auth/signin/
Content-Type: application/json

{
    "email" : "coucou@gentil.smiley",
    "password" : "mechant"
}

### whoami
GET  http://localhost:3000/auth/whoami/

### signout
POST http://localhost:3000/auth/signout/

### update user test
PATCH http://localhost:3000/auth/9
Content-Type: application/json

{
    "id": 3
}

### find user test
GET http://localhost:3000/auth/8

// ADMIN ONLY

### find users test
GET http://localhost:3000/auth/

### delete user test
DELETE http://localhost:3000/auth/6