### create user test
POST http://localhost:3000/users/signup/
Content-Type: application/json

{
    "email" : "ATNekoo@gmail.com",
    "password": "BIGGERHATERCLICKTHETRIGGER"
}

### update user test
PATCH http://localhost:3000/users/3
Content-Type: application/json

{
    "email" : "prezdelarepubliquefr@gouv.fr",
    "password" : "BRIGITTE"
}

### find user test
GET http://localhost:3000/users/4
### find users test
GET http://localhost:3000/users/