### Create user test
POST http://localhost:3000/users/signup/
Content-Type: application/json 

{
    "email":"prout@yes.com",
    "password":"DonaldTrumpISN0TAG00DGUY$!$",
    "firstName":"Donald",
    "lastName":"Trump"
}

### List all users
GET http://localhost:3000/users/users/

### Find 1 user
GET http://localhost:3000/users/5

### Update user
PATCH http://localhost:3000/users/update/2

### Delete a user
DELETE http://localhost:3000/users/deleteUser/
Content-Type: application/json

{
    "id":11
}

### Test fake user login
POST http://localhost:3000/users/login/
Content-Type: application/json 

{
    "email":"prout@yes.comm",
    "password":"DonaldTrumpISN0TAG00DGUY$!$"
}