#### USERS
### Register user test
POST http://localhost:3000/v1/auth/register
Content-Type: application/json 

{
    "email":"ohHiSS@gmail.com",
    "password":"WelcomeToRentALFE5553543////ocal",
    "firstName":"HowCanI",
    "lastName":"HelpYou"
}

### Login user test
POST http://localhost:3000/v1/auth/login
Content-Type: application/json 

{
    "email":"2383528@cegepmv.ca",
    "password":"MoiAussiJeVeuxJouer!123"
}

### Get user profile test
GET http://localhost:3000/v1/auth/profile
Cookie: session=eyJ0b2tlbiI6eyJhY2Nlc3NfdG9rZW4iOiJleUpoYkdjaU9pSklVekkxTmlJc0luUjVjQ0k2SWtwWFZDSjkuZXlKemRXSWlPakVzSW1WdFlXbHNJam9pYjJoSWFWTlRRR2R0WVdsc0xtTnZiU0lzSW5KdmJHVWlPaUoxYzJWeUlpd2lhV0YwSWpveE56YzJNVE01TlRBNUxDSmxlSEFpT2pFM056WTNORFF6TURsOS5ONkR1emJpeUVFYkVlVGNIR09lODZhTDBMeDJWendlb0ZaWG9ndWd3bFU0In19; path=/; expires=Tue, 21 Apr 2026 04:05:09 GMT; httponly,session.sig=f3YUl6D9iqrhwpdwsgJIGetZT9Y; path=/; expires=Tue, 21 Apr 2026 04:05:09 GMT; httponly

### List all users
GET http://localhost:3000/v1/users

### Find 1 user
GET http://localhost:3000/v1/users/1

### Update user
PATCH http://localhost:3000/v1/users/2

### Delete a user
DELETE http://localhost:3000/v1/users/2

#### RESERVATIONS

### List all reservations
GET http://localhost:3000/v1/reservations

### Find 1 reservation
GET http://localhost:3000/v1/reservations/3

### Create a new reservation
POST http://localhost:3000/v1/reservations
Content-Type: application/json

{
    "startDate": "2026-08-04",
    "endDate": "2026-08-06",
    "userId": 4,
    "localId": 2
}

### Update a reservation
PATCH http://localhost:3000/v1/reservations/3
Content-Type: application/json

{
    "startDate": "2026-05-01",
    "endDate": "2026-06-01"
}

### Delete a reservation
DELETE http://localhost:3000/v1/reservations/14

#### LOCALS
### Create a new local
POST http://localhost:3000/v1/locals
Content-Type: application/json

{
    "name": "Studio Ghibli",
    "address": "5545 Rue Saint-Michel, Montreal",
    "description": "Beautiful house in downtown Montreal",
    "pricePerDay": 125,
    "lat": 46.6,
    "lng": -76.7
}

### List all locals
GET http://localhost:3000/v1/locals

### Find a local by ID
GET http://localhost:3000/v1/locals/1

### Update a local
PATCH http://localhost:3000/v1/locals/1
Content-Type: application/json

{
    "pricePerDay": 99.99,
    "description": "Beautiful studio with wifi and AC"
}

### Delete a local
DELETE http://localhost:3000/v1/locals/4

#### PAYMENTS
### Pay reservation
POST http://localhost:3000/v1/payments/7